CREATE DATABASE libreria_cf; -- CREAMOS LA BASE DE DATOS USANDO EL COMANDO "CREATE DATABASE NOMBRE_BD;"

USE libreria_cf; --  DECLARAMOS QUE USAREMOS LA BASE DE DATOS CON EL COMANDO " USE NOMBRE-BD;"

CREATE TABLE IF NOT EXISTS AUTORES
(                                                             -- IF NO EXIST NOS PERMITE CREAR LA TABLA CADA VEZ QUE SEA NECESARIO PERO NO EXISTA
    AUTOR_ID         INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, -- LA LLAVE PRIMARIA SE DEFINE MEDIANTE EL COMANDO  "PRIMARY KEY" LAS LLAVES POR LO GENERAL SON DE TIPO DE DATO ENTERO "INT" AUTO_INCREMENT NOS PERMITE QUE SE ASIGENE AUTOMATICAMENTE UN DATO COMO ID QE AUMENTA EN 1 CADA VEZ QUE SE AÑADE UN NUEVO DATO
    NOMBRE           VARCHAR(25) NOT NULL,
    APELLIDO         VARCHAR(25) NOT NULL,
    SEUDONIMO        VARCHAR(50) UNICODE,
    GENERO           ENUM ('M', 'F'),                         -- ENUM NOS PERMITE DEFINIR LOS UNICOS DATOS PERMITDOS O SEA M Y F
    FECHA_NACIMIENTO DATE        NOT NULL,
    PAIS_ORIGEN      VARCHAR(40) NOT NULL,
    FECHA_CREACION   DATETIME DEFAULT CURRENT_TIMESTAMP,       -- CURRENT_TIMESTAMP NSO PERMITE TOMAR LA FECHA Y HORA DEL SISTEMA
    CONSTRAINT UNIQUE_COMBINATION UNIQUE(NOMBRE,APELLIDO)  -- CONSTRAINT UNIQUE_COMBINATION UNIQUE (NOMBRE_CAMPO1, NOMBRE_CAMPO2) NOS PERMITE DEFINIR UNICOS VARIOS CAMPOS DE UNA TABLA
);

CREATE TABLE IF NOT EXISTS LIBROS
(

    LIBRO_ID          INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    AUTOR_ID          INT UNSIGNED NOT NULL,
    TITULO            VARCHAR(50)  NOT NULL,
    DESCRIPCION       VARCHAR(250),
    PAGINAS           INTEGER UNSIGNED,
    FECHA_PUBLICACION DATE         NOT NULL,
    FECHA_CREACION    DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES (AUTOR_ID)

);


/* INSERTAMOS LOS DATOS EN AUTORES DONDE SOLO UNO PODRÍA SER NULO EL CUAL ES EL SEUDONIMO PERO NO LO HEMOS DEJADO NULO */

INSERT INTO AUTORES (NOMBRE, APELLIDO, SEUDONIMO, GENERO, FECHA_NACIMIENTO, PAIS_ORIGEN) -- EL AUTOR ID NO SE HA PUESTO YA QUE ESTE SI RECORDAMOS LO COLOCAMOS COMO AUTO_INCREMENT
VALUES ('Stephen Edwin', 'King', 'Richard Bachman', 'M', '1947-09-27', 'USA'),
       ('Joanne', 'Rowling', 'J.R Rowling', 'F', '1947-09-27', 'Reino undido');

INSERT INTO AUTORES(NOMBRE, APELLIDO, SEUDONIMO, GENERO, FECHA_NACIMIENTO, PAIS_ORIGEN)  -- ESTO ES UNA PRUEBA PARA VER QUE NO SE PODRÀ INGRESAR DATOS DUPLICADOS EN CUANTO AL NOMBRE Y APPELIDO DE UN AUTOR
VALUES  ('Stephen Edwin', 'King', 'Richard Bachman', 'M', '1947-09-27', 'USA');

/* INSERTAMOS DATOS EN LA TABALA DE LIBROS */

INSERT INTO LIBROS (AUTOR_ID, TITULO, FECHA_PUBLICACION)
VALUES (1, 'CARRIE', '1974-01-01'),
       (1, 'El misterio de salmes lot', '1975-01-01'),
       (2, 'HarryPotter y la piedra filosofal', '1997-09-30'),
       (2, 'HarryPotter y la camara secreta', '1998-07-2');



/* MODIFICADOR DE TABLAS */ -- LOS MODIFICADORES DE TABLA NOS PERMITEN MODIFICAR, AGREGAR Y ELIMINAR YA SEAN DATOS, TABLAS O COLUMNAS

ALTER TABLE LIBROS ADD VENTAS INT UNSIGNED NOT NULL; -- AGREGAREMOS UN COLUMNA A NUESTRA TABLA LIBROS LA CUAL NO RECIBIRA DATOS NEGATIVOS NI NULOS
    desc LIBROS;







/* RECURRING EXECUTE */

SHOW TABLES;
DROP DATABASE libreria_cf;

DROP TABLE AUTORES;
DROP TABLE LIBROS;


SHOW DATABASES;
SELECT *
FROM AUTORES;

DELETE
FROM AUTORES

WHERE AUTOR_ID = 1;

DESC LIBROS;

SELECT NOW();
